name: Publish to npm

on:
  push:
    branches: [master]

jobs:
  publish:
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        registry-url: 'https://registry.npmjs.org'

    - name: Setup
      run: npm ci

    - name: Publish
      run: npm publish
      env: 
        NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}

